# Generated by Django 5.2.7 on 2025-11-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clientfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='quota_limit',
            field=models.BigIntegerField(default=5368709120, help_text='Storage quota in bytes'),
        ),
    ]
