# Generated by Django 5.2.7 on 2025-11-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clientprofile_quota_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='quota_limit',
            field=models.BigIntegerField(help_text='Storage quota in bytes. e.g., 5*1024*1024*1024 for 5GB'),
        ),
    ]
