# Generated by Django 5.2.7 on 2025-11-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_clientprofile_quota_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='relative_path',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
